### ISSUE TITLE
staging is missing

### ISSUE THREAD

**Issue by soaErikNord** [ForgeRock/frstack#10]
I'm getting the following exception when I run `vagrant up`:

```
Bringing machine 'oisserver' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The host path of the shared folder is missing: ../staging
```

I've added a staging directory to the ansible, vagrant and vagrant-ha directories with no luck.  I'm using your latest commits.

Thoughts?

**Comment by wstrange** [comment]
Can you try to create the directory one level higher? Let me know if that works.

**Comment by soaErikNord** [comment]
closer:
```
TASK: [tomcat | No staged archive found. Downloading] *************************
failed: [oisserver] => {"dest": "/var/tmp/apache-tomcat-8.0.15.tar.gz", "failed": true, "response": "HTTP Error 404: Not Found", "state": "absent", "status_code": 404, "url": "http://apache.cs.utah.edu/tomcat/tomcat-8/v8.0.15/bin/apache-tomcat-8.0.15.tar.gz"}
msg: Request failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/Users/enord/frstack.retry

oisserver                  : ok=34   changed=28   unreachable=0    failed=1

Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

**Comment by soverbosch** [comment]
Looks like the download link to tomcat is not valid anymore! change it to a
valid one and you are back again

[image: [DIR]] v8.0.18/
<http://apache.cs.utah.edu/tomcat/tomcat-8/v8.0.18/>
26-Jan-2015 06:41    -   [image: [DIR]] v8.0.20/
<http://apache.cs.utah.edu/tomcat/tomcat-8/v8.0.20/>


2015-03-06 15:52 GMT+01:00 soaErikNord <notifications@github.com>:

**Comment by wstrange** [comment]
I fixed up .gitignore so it commits the staging/ dir - but not the contents

Also fixed up the tomcat version

Thanks for the issue report - please feel free to send pull requests if you find something broken! 
This is very much a work in progress...
