### ISSUE TITLE
Ansible task failing @ setup opendj 

### ISSUE THREAD

**Issue by amitoj** [ForgeRock/frstack#13]
The error message is

```
TASK: [opendj | setup opendj] ************************************************* 
failed: [oisserver] => {"changed": true, "cmd": ["/opt/ois/opendj/setup", "--cli", "--propertiesFilePath", "/tmp/opendj.properties", "--acceptLicense", "--no-prompt"], "delta": "0:00:01.884770", "end": "2015-05-02 17:52:30.284493", "rc": 2, "start": "2015-05-02 17:52:28.399723", "warnings": []}
stderr: An error occurred while parsing the command-line arguments:  An unexpected error occurred while attempting to initialize the command-line arguments:  
You have chosen to enable SSL or StartTLS.  You must specify which type of certificate you want the server to use
```

I changed the version of opendj nightly build from 2.7.0 to 3.0.0 because that's the only version available for download.

Thanks,
Amitoj

**Comment by wstrange** [comment]
Hi Amitoj

I think some of the cli args must have changed with the newer nightly builds. You can try to edit the vars/nightly and set it to use a "staged" version of OpenDJ 2.6.0. I just tested with 2.6.2 and it worked.

We definitely need a strategy to keep up with version changes.  The current process assumes that things like CLI args don't change between releases. 

I need to think on this (possibly use something like Docker to bake in the right versions of everything)

**Comment by amitoj** [comment]
Hi Warren,

Thanks, I'll try to download OpenDJ 2.6.2 if it's available.
