### ISSUE TITLE
vagrant provision errors out in Win 7 host

### ISSUE THREAD

**Issue by rsbhat17** [ForgeRock/frstack#17]
I get the below error when I try to run vagrant provision command from babun (Cygwin variant). I checked all the paths seems to be correct.

{ vagrant } master » vagrant provision                               
==> oisserver: Running provisioner: ansible...
PYTHONUNBUFFERED=1 ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_NOCOLOR=true ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o IdentitiesOnly=yes -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --user=vagrant --connection=ssh --timeout=30 --limit='oisserver' --inventory-file=C:/Sites/frstack/vagrant/.vagrant/provisioners/ansible/inventory --sudo -vvv ../ansible/frstack.yml
The system cannot find the path specified.
Ansible failed to complete successfully. Any error output should be visible above. Please fix these errors and try again.

**Comment by wstrange** [comment]
I am guessing this is a Windows pathing issue. 

I'd strongly suggest running this on Linux (perhaps under Virtualbox)

**Comment by rsbhat17** [comment]
Thanks Warren, I was able to make progress after running this on a Centos 6.5 VM.
