### ISSUE TITLE
Error on vagrant provisioning

### ISSUE THREAD

**Issue by DiegoRam** [ForgeRock/frstack#18]
Hi Guys!
I'm not quite sure if I did smth worong but when I got this error on vagrant provisioning process:

TASK: [install-base-yum | Install required packages. This takes a while - be patient] ***
failed: [oisserver] => (item=unzip,git,wget,haproxy,httpd,gpg,java-1.8.0-openjdk-headless.x86_64,python-pip,docker,bzip2) => {"failed": true, "item": "unzip,git,wget,haproxy,httpd,gpg,java-1.8.0-openjdk-headless.x86_64,python-pip,docker,bzip2", "parsed": false}
BECOME-SUCCESS-llgnanspxbofgvnbydlcmoddloaexyqf
/bin/sh: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
Traceback (most recent call last):
  File "/home/vagrant/.ansible/tmp/ansible-tmp-1443621133.5-47675586902387/yum", line 27, in <module>
    import yum
ImportError: No module named yum
OpenSSH_6.2p2, OSSLShim 0.9.8r 8 Dec 2011
debug1: Reading configuration data /Users/diegoram/.ssh/config
debug1: Reading configuration data /etc/ssh_config
debug1: /etc/ssh_config line 20: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 127.0.0.1 closed.

FATAL: all hosts have already failed -- aborting

Any idea?

**Comment by wstrange** [comment]
Hi Diego

The latest image is baed on Fedora 22, which now uses 'dnf' instead of yum. 

Can you ensure you have the most recent version of ansible (1.9.x).  And also make sure you have pulled the latest changes from this repo.

Let me know if that gets you further

**Comment by DiegoRam** [comment]
Thanks @wstrange .
Actually I have Ansible 1.9.2 installed.
Besides I'm using OSX, I dont know if that could be part of the cause.

**Comment by wstrange** [comment]
Hmm

That error looks to me like some kind of Ansible install issue:
"import yum
ImportError: No module named yum"

How did you install Ansible?

I used brew to install ansible


Ansible does need proper PATHing setup for including modules. Perhaps it is not picking up the install?

**Comment by richardTowers** [comment]
I also saw this issue on an OS X host, ansible 1.9.1 installed with homebrew.

I worked around it by replacing all `yum` tasks with `dnf` tasks:

```
find ansible -name '*.yml' | xargs sed -i~ "s/yum:/dnf:/g"
```

Presumably this is something that ansible should work out by itself though?

**Comment by tnory56** [comment]
I had to do the same work around to make it work on ansible 1.9.3

**Comment by wstrange** [comment]
Ahh, yes.  yum is replaced by dnf in Fedora 22+.  I pushed an update that changes all yum instances to dnf. 

When Ansible 2.0 is released they have a more generic 'package' command that should take care of the differences
