### ISSUE TITLE
Failure talking to dnf: 'Base' object has no attribute 'rpmdb'

### ISSUE THREAD

**Issue by richardTowers** [ForgeRock/frstack#19]
I was seeing this error when provisioning on fedora 22 after the switch to DNF.

```
failed: [oisserver] => (item=unzip) => {"failed": true, "item": "unzip"}
msg: Failure talking to dnf: 'Base' object has no attribute 'rpmdb'
failed: [oisserver] => (item=git) => {"failed": true, "item": "git"}
msg: Failure talking to dnf: 'Base' object has no attribute 'rpmdb'
```

It looked like ansible/ansible-modules-extras#471, so I took the suggested fix by adding

```
- name: Install Yum Utilities
  sudo: true
  shell: dnf install yum-utils -y
  args:
    creates: /usr/bin/repomanage
```

to the top of `ansible/roles/install-base-centos/tasks/main.yml`. This seems to have resolved the issue and everything provisions correctly.

Can't say I really understand what the problem is here, or how to fix it properly, but I thought I'd post in case anyone else encounters the same issue.

(OS X host, ansible 1.9.1, Vagrant 1.7.4)

**Comment by wstrange** [comment]
Thanks @richardTowers . I committed a fix with your suggested work around. 

Will revisit when Ansible 2.0's package module is ready.
