### ISSUE TITLE
Current stack is broken

### ISSUE THREAD

**Issue by ekarlso** [ForgeRock/frstack#22]
Hi, the current stack when doing ./frstack breaks, any ideas on how to get it up?

**Comment by wstrange** [comment]
Hi - yes things are little broken right now. 

I am planning on updating to Ansible 2.0 in the new year, and updating the base image to Fedora23. 

Currently I am prioritizing getting the stack working on Docker / Kubernetes - as this is a more promising long term direction.

I am happy to accept pull requests if you have immediate fixes that you would like to see incorporated.

**Comment by wstrange** [comment]
Updated to Fedora 23 / Ansible 2.0. Works

Please try again.
