### ISSUE TITLE
Able to install OpenAm but not able to login

### ISSUE THREAD

**Issue by ranajit-jana** [ForgeRock/frstack#23]
I only wanted open am to be installed thus able to install the same via the ansible script. I have used the version 14 Snapshot from the maven repository. But i am not able to login with the credential 

amAdmin / password

I rechecked and the variable is set as below

amadmin_password: password

Let me know if i need to do anything more.

The target machine is not showing signs of error. but the login is failing

**Comment by wstrange** [comment]
Without more information it is hard to tell what is happening. Look in the logs ~/openam/openam/logs 

Note that this has not been tested yet with some of the newer nightly builds - so it is probably broken.

**Comment by wstrange** [comment]
I just updated the installer to Ansible 2.0 / Fedora 23, and reran from scratch.  OpenAM comes up OK for me.

(Note:  you might try amadmin - not amAdmin. It should not make any difference - but best to stick to lower case)


Try this again. If you still have issues please provide detailed debug logs.
