### ISSUE TITLE
Syntax error on line 40 of /etc/httpd/conf.modules.d/00-base.conf: Cannot load modules/mod_http2.so into se..._stream_priority

### ISSUE THREAD

**Issue by darkedges** [ForgeRock/frstack#31]
Morning,
I am receiving this error on startup of the httpd service.

```
Syntax error on line 40 of /etc/httpd/conf.modules.d/00-base.conf: Cannot load modules/mod_http2.so into se..._stream_priority
```

Any ideas?

**Comment by darkedges** [comment]
After I performed the following
```
dnf update
```
I was able to get past that error. Guess there are some library udpates that need to occur to get this build working. Will submit a patch shortly.

**Comment by tcz001** [comment]
full error message is `httpd: Syntax error on line 56 of /etc/httpd/conf/httpd.conf: Syntax error on line 40 of /etc/httpd/conf.modules.d/00-base.conf: Cannot load modules/mod_http2.so into server: /etc/httpd/modules/mod_http2.so: undefined symbol: nghttp2_session_change_stream_priority`

**Comment by tcz001** [comment]
the missing `nghttp2_session_change_stream_priority` is defined in `libnghttp2`, so update this lib should fix this problem

**Comment by wstrange** [comment]
If you could submit a PR that would be great.

**Comment by tcz001** [comment]
@wstrange Hi, I have submitted a pull request for this issue, please review
